apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example
  description: example.com
  links:
    - url: https://dashboard.example.com
      title: My Dashboard
      icon: dashboard
  annotations:
    backstage.io/techdocs-ref: value
spec:
  type: website
  lifecycle: production
  owner: user:guest
